import Head from 'next/head'

import { Input } from '../components/Input'
import { Button } from '../components/Button'

const Home = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="h-screen flex  w-screen item-center">
                <div className="bg-blue-800 flex-1 hidden xl:block"></div>
                <div className="p-10 flex flex-col w-full xl:w-[50%] gap-5 h-full justify-center items-center ">
                    <div className="w-[400px]">
                        <h1 className="text-3xl font-semibold">
                            Bem-vindo(a) de volta!
                        </h1>
                    </div>
                    <form
                        action=""
                        className="w-[400px] flex flex-col space-y-6"
                    >
                        <Input
                            placeholder="Digite seu e-mail"
                            label="E-mail"
                            name="email"
                        />
                        <Input
                            placeholder="Digite seu senha"
                            label="Senha"
                            name="senha"
                        />

                        <div className="flex flex-col gap-4">
                            <Button text="Entrar" variant="blue" />

                            <div className="border border-b-gray-600/[0.4] w-[400px] flex justify-center"></div>
                            <Button
                                icon="/googleLogo.svg"
                                text="Entrar com o Google"
                                variant="outlineGoogle"
                            />
                            <Button
                                icon="/GitHub-Mark.png"
                                text="Entrar com o GitHub"
                                variant="outlineGithub"
                            />
                        </div>
                    </form>

                    <div className="flex gap-2 text-sm font-light mt-5">
                        <h4>Não tem conta?</h4>
                        <a
                            href="/signup"
                            className="transition-all text-sky-700 font-normal hover:text-sky-400"
                        >
                            Inscreva-se
                        </a>
                    </div>
                </div>
            </main>
        </>
    )
}

export default Home
