import Head from "next/head";


const  Home = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main  className="h-screen flex w-screen item-center p-5">
        <form action="" className="w-[460px]">


          <div className="border border-black rounded-2xl ">
            <span className="mx-4 px-2 absolute top-2 bg-white  ">E-mail</span>
            <input type="text" placeholder="E-mail" className="flex item-start focus:outline-0 p-4 w-full rounded-2xl" />
          </div>


        </form>
      </main>
    </>
  );
}

export default Home
