import Head from "next/head";

import { Input } from '../components/Input'
import { Button } from '../components/Button'

const Home = () => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="h-screen flex  w-screen item-center">
                <div className="bg-blue-800 flex-1"></div>
                <div className="p-10 flex flex-col gap-5 h-full justify-center ">
                    <div>
                        <h1 className="text-3xl font-semibold">
                            Bem-vindo(a) de volta!
                        </h1>
                    </div>
                    <form
                        action=""
                        className="w-[400px] flex flex-col space-y-6"
                    >
                        <Input
                            placeholder="Digite seu e-mail"
                            label="E-mail"
                            name="email"
                        />
                        <Input
                            placeholder="Digite seu senha"
                            label="Senha"
                            name="senha"
                        />

                        <div className="flex flex-col gap-4">
                            <Button text="Entrar" variant="blue" />
                            <Button
                                text="Entrar com o Google"
                                variant="outline"
                            />
                        </div>
                    </form>
                </div>
            </main>
        </>
    )
}

export default Home
